
package TP2_Grupo_AaronKevinRigoberto;


import static TP2_Grupo_AaronKevinRigoberto.GestorCliente.listaClientes;
import static TP2_Grupo_AaronKevinRigoberto.GestorEmpleado.listaEmpleado;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author kevin
 */
public class GestionDeReservaciones extends javax.swing.JFrame {
    
    DefaultTableModel modelo;

    private PanelMenuPrincipal menu;
    private DefaultTableModel modeloTabla;
      
    public GestionDeReservaciones(PanelMenuPrincipal menu) {
        initComponents();
        this.setLocationRelativeTo(null);
        configurarFechaHora();
        configurarTabla();
        
        cmbCliente = new javax.swing.JComboBox<>();
        cmbEmpleado = new javax.swing.JComboBox<>();
        cmbServicio = new javax.swing.JComboBox<>();
        this.menu = menu;
    }
     private void configurarFechaHora() {
     Date hoy = new Date();
    SpinnerDateModel modelo = new SpinnerDateModel(hoy, hoy, null, Calendar.MINUTE);
    spnFechaHora.setModel(modelo);

    JSpinner.DateEditor editor = new JSpinner.DateEditor(spnFechaHora, "dd/MM/yyyy HH:mm");
    spnFechaHora.setEditor(editor);

    JFormattedTextField campo = editor.getTextField();
    campo.setFocusLostBehavior(JFormattedTextField.COMMIT);

    campo.addKeyListener(new KeyAdapter() {
        @Override
        public void keyPressed(KeyEvent e) {
            int pos = campo.getCaretPosition();
            String texto = campo.getText();

            if (e.getKeyCode() == KeyEvent.VK_BACK_SPACE && pos > 0) {
                char anterior = texto.charAt(pos - 1);

                if (anterior == '/' || anterior == ':' || anterior == ' ') {
                    e.consume();
                }
            }
        }
    }); }   
    private void configurarTabla() {
        modelo = new DefaultTableModel();
        modelo.addColumn("ID Reserva");
        modelo.addColumn("Cliente");        modelo.addColumn("Empleado");
        modelo.addColumn("Servicio");
        modelo.addColumn("Duracion");
        modelo.addColumn("Fecha/Hora entrada");
        modelo.addColumn("Fecha/Hora Salida");
        tblMostrarReservaciones.setModel(modelo);
    }
         private void refrescarTabla() {

    modeloTabla.setRowCount(0);
   
    for (Empleado empleado : listaEmpleado) {
        modeloTabla.addRow(new Object[]{
            empleado.getIdentificador(),
            empleado.getNombre(),empleado.getNumeroTelefono(),
            empleado.getEspecialidad()
        });}} 
         private void cargarCombos() {

    cmbCliente.removeAllItems();
    for (Cliente cliente : GestorCliente.getCliente()) {
        cmbCliente.addItem(cliente.getNombre()); // OBJETO
    }

    cmbEmpleado.removeAllItems();
    for (Empleado empleado : GestorEmpleado.getEmpleados()) {
        cmbEmpleado.addItem(empleado); // OBJETO
    }

    cmbServicio.removeAllItems();
    for (Servicio servicio : GestorServicio.getServicios()) {
        cmbServicio.addItem(servicio); // OBJETO
    }

    cmbEstado1.removeAllItems();
    cmbEstado1.addItem("Pendiente");
    cmbEstado1.addItem("Completada");
    cmbEstado1.addItem("Cancelada");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblGestiondeReservacion = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JPanel();
        cmbCliente = new javax.swing.JComboBox<>();
        lblID = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblServicio = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        cmbServicio = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        spnFechaHora = new javax.swing.JSpinner();
        btnAgregar1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        cmbEmpleado = new javax.swing.JComboBox<>();
        cmbEstado1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMostrarReservaciones = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGestiondeReservacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGestiondeReservacion.setForeground(new java.awt.Color(0, 153, 255));
        lblGestiondeReservacion.setText("Gestion de Reservacion");
        jPanel3.add(lblGestiondeReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 23, 206, -1));

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });
        FondoBlanco.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 140, 30));

        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("ID:");
        FondoBlanco.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 50, -1));

        lblCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblCliente.setText("Cliente:");
        FondoBlanco.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 60, -1));

        lblServicio.setForeground(new java.awt.Color(0, 0, 0));
        lblServicio.setText("Servicio");
        FondoBlanco.add(lblServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 50, -1));

        lblEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpleado.setText("Empleado:");
        FondoBlanco.add(lblEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 70, -1));

        lblHora.setForeground(new java.awt.Color(0, 0, 0));
        lblHora.setText("Fecha y hora:");
        FondoBlanco.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, -1));

        estado.setForeground(new java.awt.Color(0, 0, 0));
        estado.setText("Estado:");
        FondoBlanco.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 76, -1));

        cmbServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbServicioActionPerformed(evt);
            }
        });
        FondoBlanco.add(cmbServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 140, -1));

        txtID.setColumns(5);
        FondoBlanco.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, -1));
        FondoBlanco.add(spnFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, -1));

        btnAgregar1.setText("Buscar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        FondoBlanco.add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 100, -1));
        FondoBlanco.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, -1));

        lblBuscar.setForeground(new java.awt.Color(0, 0, 0));
        lblBuscar.setText("Buscar:");
        FondoBlanco.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, -1));

        cmbEmpleado.setPreferredSize(new java.awt.Dimension(70, 20));
        FondoBlanco.add(cmbEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 140, 30));

        cmbEstado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstado1ActionPerformed(evt);
            }
        });
        FondoBlanco.add(cmbEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 140, 30));

        jPanel3.add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 66, 490, 310));

        tblMostrarReservaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMostrarReservaciones);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 570, 100));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 100, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 100, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 100, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClienteActionPerformed


    private void limpiarCampos() {
        txtID.setText("");
        txtBuscar.setText("");
        txtID.setEditable(true);
        if(cmbCliente.getItemCount() > 0) cmbCliente.setSelectedIndex(0);
        if(cmbCliente.getItemCount() > 0) cmbCliente.setSelectedIndex(0);
        if(cmbServicio.getItemCount() > 0) cmbServicio.setSelectedIndex(0);
        if(cmbCliente.getItemCount() > 0) cmbCliente.setSelectedIndex(0);
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
    // 1. Obtener los objetos seleccionados del combo
    Cliente cliente = (Cliente) cmbCliente.getSelectedItem();
    Empleado empleado = (Empleado) cmbEmpleado.getSelectedItem();
    Servicio servicio = (Servicio) cmbServicio.getSelectedItem();

    // 2. Obtener ID, fecha, hora, etc …
    String id = txtID.getText();
    Date seleccion = (Date) spnFechaHora.getValue();

        if (seleccion == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha y hora.");
            return;
        }
        LocalDateTime fecha = seleccion.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDateTime();
        if (fecha.isBefore(LocalDateTime.now())) {
            JOptionPane.showMessageDialog(this, "No puede seleccionar una fecha pasada.");
            return;
        }
        
    Reservacion nuevaReservacion;// 3. Crear la reservación
    nuevaReservacion = new Reservacion(id, cliente,empleado, servicio, fecha);

    // 4. Guardarla
    GestorReservaciones.agregarReservacion(nuevaReservacion);

    // 5. Aviso
    JOptionPane.showMessageDialog(this, "Reservación agregada correctamente");

    // 6. Refrescar tabla
    refrescarTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int fila = tblMostrarReservaciones.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar este cliente?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                String id = txtID.getText();

                boolean ok = GestorCliente.eliminarCliente(id);

                if (ok) {
                    JOptionPane.showMessageDialog(this, "Servicio eliminado.");
                    refrescarTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar.");
                }

                limpiarCampos();
                refrescarTabla();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void cmbServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbServicioActionPerformed

    private void cmbEstado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstado1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       new PanelMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<Empleado> cmbEmpleado;
    private javax.swing.JComboBox<String> cmbEstado1;
    private javax.swing.JComboBox<Servicio> cmbServicio;
    private javax.swing.JLabel estado;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblGestiondeReservacion;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JSpinner spnFechaHora;
    private javax.swing.JTable tblMostrarReservaciones;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
