
package TP2_Grupo_AaronKevinRigoberto;

import TP2_Grupo_AaronKevinRigoberto.GestorServicio;
import javax.swing.JOptionPane;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin
 */

public class GestionDeServicios extends javax.swing.JFrame {
                                        
     private PanelMenuPrincipal menu;               
     private DefaultTableModel modeloTabla;                  
     ArrayList<Servicio> listaServicios;
     
    public GestionDeServicios(PanelMenuPrincipal menu) {
        initComponents();
        this.menu = menu;
        configurarTabla();
        configurarComboDuracion();
        agregarEventoSeleccionTabla();

    }
    
    private void agregarEventoSeleccionTabla() {
        
    tblMostrarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {

            int fila = tblMostrarDatos.getSelectedRow();

            if (fila >= 0) {

                // ID
                txtIDServicio.setText(
                    modeloTabla.getValueAt(fila, 0).toString()
                );

                // Nombre
                txtNombreServicio.setText(
                    modeloTabla.getValueAt(fila, 1).toString()
                );

                // Duración
                String dur = modeloTabla.getValueAt(fila, 2).toString();
                cmbDuracion.setSelectedItem(dur);

                // Costo → quitarle "₡"
                String costo = modeloTabla.getValueAt(fila, 3).toString();
                costo = costo.replace("₡", "");
                txtCostoBase.setText(costo.trim());
            }
        }
    });
}
    private void configurarComboDuracion() {

    cmbDuracion.removeAllItems();
    cmbDuracion.addItem("Elegir...");

    // Minutos (10–50)
    for (int i = 10; i <= 50; i += 10) {
        cmbDuracion.addItem(i + " min");
    }

    // Horas (1h–6h)
    for (int h = 1; h <= 6; h++) {
        cmbDuracion.addItem(h + " h");
    }
    for (int minutos = 60; minutos <= 360; minutos += 30) {
        int horas = minutos / 60;
        int resto = minutos % 60;
        if (resto == 0) {
            cmbDuracion.addItem(horas + " h");
        } else {
            cmbDuracion.addItem(horas + " h " + resto + " min");}}}
    
    
    private void configurarTabla() {
        
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Duracion (min/h)");
        modeloTabla.addColumn("Costo");
        tblMostrarDatos.setModel(modeloTabla);}
    
    private void refrescarTabla() {

    modeloTabla.setRowCount(0);

    for (Servicio servicio : GestorServicio.getServicios()) {
        modeloTabla.addRow(new Object[]{
            servicio.getIdentificador(),
            servicio.getNombre(),
            servicio.getDuracionMinutos(),
            servicio.getCosto() + "₡"
        });
    }
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblDatosServicios = new javax.swing.JLabel();
        lblIDServicio = new javax.swing.JLabel();
        lblNombreServicio = new javax.swing.JLabel();
        lblCostoBase = new javax.swing.JLabel();
        lblTipoDeServicio = new javax.swing.JLabel();
        txtIDServicio = new javax.swing.JTextField();
        txtNombreServicio = new javax.swing.JTextField();
        txtCostoBase = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        lblDuración = new javax.swing.JLabel();
        cmbTipoDeServicio = new javax.swing.JComboBox<>();
        cmbDuracion = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        ScrollTabla = new javax.swing.JScrollPane();
        tblMostrarDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Gestion de Servicio");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblDatosServicios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDatosServicios.setText("Datos del Servicio");

        lblIDServicio.setForeground(java.awt.Color.black);
        lblIDServicio.setText("ID");

        lblNombreServicio.setText("Nombre del Servicio:");

        lblCostoBase.setText("Costo Base (₡):");

        lblTipoDeServicio.setText("Tipo de Servicios:");

        txtIDServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDServicioActionPerformed(evt);
            }
        });

        txtNombreServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreServicioActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        lblDuración.setText("Duracion (minutos/horas):");

        cmbTipoDeServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Opcion", "Trantamiento Capilar", "Corte de Cabello", "Manicure" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblDatosServicios))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCostoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDuración)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbDuracion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(228, 228, 228))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblIDServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCostoBase)
                                            .addComponent(txtIDServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)))
                                .addComponent(btnListar))
                            .addComponent(lblNombreServicio)
                            .addComponent(cmbTipoDeServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipoDeServicio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblDatosServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIDServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblTipoDeServicio)
                .addGap(18, 18, 18)
                .addComponent(cmbTipoDeServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnListar)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCostoBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCostoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDuración)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        tblMostrarDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Duración (min)", "Costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollTabla.setViewportView(tblMostrarDatos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ScrollTabla))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(143, 143, 143))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDServicioActionPerformed

    private void txtNombreServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreServicioActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
       refrescarTabla();     // TODO add your handling code here:
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    String id = txtIDServicio.getText().trim();
    String nombre = txtNombreServicio.getText().trim();
    String selccionDuracion = (String) cmbDuracion.getSelectedItem();
    double costoBase; int duracion;
    // validar ID unico
    if (GestorServicio.existeID(id)) {
        JOptionPane.showMessageDialog(this,
                "El identificador ya existe. Ingrese uno diferente.",
                "ID duplicado",
                JOptionPane.WARNING_MESSAGE);return;}
       
        // condicionales
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this,"El ID no puede estar vación.");
        return;} 
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this,"El nombre no puede estar vacío.");
        return;}
        if (selccionDuracion.contains("min")) {
        duracion = Integer.parseInt(selccionDuracion.replaceAll("[^0-9]", ""));
         } else {
        int horas = Integer.parseInt(selccionDuracion.replaceAll("[^0-9]", ""));
        duracion = horas * 60;
        }
        if (duracion <= 0) {
            JOptionPane.showMessageDialog(this,"La duración debe ser mayor que 0.");
        return; }
        
        try {
            costoBase = Double.parseDouble(txtCostoBase.getText());
            if (costoBase <= 0) {
                JOptionPane.showMessageDialog(this,"El costo debe ser mayor que 0.");
            }
        } catch (NumberFormatException e) { JOptionPane.showMessageDialog(this,
                "Ingrese un costo válido. "); return ;}
        
        if (GestorServicio.buscarPorID(id) != null) {
            JOptionPane.showMessageDialog(this,"Ya existe un servicio con ese ID."); return;
        }
        String tipo = cmbTipoDeServicio.getSelectedItem().toString();
        Servicio nuevoServicio;
        
            switch (tipo) {
            case "Corte de Cabello":
                nuevoServicio = new CorteCabello(id, nombre,duracion,costoBase,false); break;
            case "Trantamiento Capilar":
                nuevoServicio = new TratamientoCapilar(tipo, nombre, duracion, costoBase); break;
            case "Manicure": 
                nuevoServicio = new TratamientoCapilar(tipo, nombre, duracion, costoBase); break;
            
            default: JOptionPane.showMessageDialog(this,"Tipo no reconocido."); return;}
       
        GestorServicio.agregarServicio(nuevoServicio);
        
        JOptionPane.showMessageDialog(this, "Servicio agregado corecamente");
        
     
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
                                       
    String id = txtIDServicio.getText().trim();
    String nombre = txtNombreServicio.getText().trim();
    String seleccionDuracion = (String) cmbDuracion.getSelectedItem();

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar un ID.");
        return;
    }
    // Validar que el servicio exista
    Servicio servicio = GestorServicio.buscarPorID(id);
    if (servicio == null) {
        JOptionPane.showMessageDialog(this,
                "No existe un servicio con ese identificador.",
                "Modificar servicio",
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    // Validar nombre
    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
        return;
    }
    // Procesar duración
    int duracion;
    try {
        if (seleccionDuracion.endsWith("min")) {
            duracion = Integer.parseInt(seleccionDuracion.replace(" min", "").trim());
        } else if (seleccionDuracion.endsWith("h")) {
            int horas = Integer.parseInt(seleccionDuracion.replace(" h", "").trim());
            duracion = horas * 60;
        } else {
            JOptionPane.showMessageDialog(this,
                    "Formato de duración inválido.",
                    "Error en duración",
                    JOptionPane.ERROR_MESSAGE);return;}
    } catch (NumberFormatException ex) {  JOptionPane.showMessageDialog(this, "Duración inválida. Debe ser un número.","Error en duración",JOptionPane.ERROR_MESSAGE);return;
    }

    if (duracion <= 0) {JOptionPane.showMessageDialog(this,"La duración debe ser mayor a 0.","Duración inválida",JOptionPane.ERROR_MESSAGE);  return;
   }

    // Validar costo
    double costo;
    try {
        costo = Double.parseDouble(txtCostoBase.getText().trim());
        if (costo <= 0) {
            JOptionPane.showMessageDialog(this, "El costo debe ser mayor a 0.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese un costo válido.");
        return;
    }

    // Modificar usando el Gestor
    boolean ok = GestorServicio.modificarServicio(id, nombre, duracion, costo);

    if (ok) {
        JOptionPane.showMessageDialog(this,
                "Servicio modificado correctamente.",
                "Modificar servicio",
                JOptionPane.INFORMATION_MESSAGE);
        refrescarTabla(); // 👈 IMPORTANTE
    } else {
        JOptionPane.showMessageDialog(this,
                "No se pudo modificar el servicio.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    
    String id = txtIDServicio.getText();

    boolean ok = GestorServicio.eliminarServicio(id);

    if (ok) {
        JOptionPane.showMessageDialog(this, "Servicio eliminado.");
        refrescarTabla();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo eliminar.");
    }


        
// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
        new PanelMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollTabla;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbDuracion;
    private javax.swing.JComboBox<String> cmbTipoDeServicio;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCostoBase;
    private javax.swing.JLabel lblDatosServicios;
    private javax.swing.JLabel lblDuración;
    private javax.swing.JLabel lblIDServicio;
    private javax.swing.JLabel lblNombreServicio;
    private javax.swing.JLabel lblTipoDeServicio;
    private javax.swing.JTable tblMostrarDatos;
    private javax.swing.JTextField txtCostoBase;
    private javax.swing.JTextField txtIDServicio;
    private javax.swing.JTextField txtNombreServicio;
    // End of variables declaration//GEN-END:variables
}
 
