
package TP2_Grupo_AaronKevinRigoberto;


import static TP2_Grupo_AaronKevinRigoberto.GestorEmpleado.listaEmpleado;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author kevin
 */
public class GestionDeReservaciones extends javax.swing.JFrame {
    
    DefaultTableModel modelo;

    private PanelMenuPrincipal menu;
    private DefaultTableModel modeloTabla;
      
    public GestionDeReservaciones(PanelMenuPrincipal menu) {
        initComponents();
        this.setLocationRelativeTo(null);
        configurarTabla();
        cmbCliente.setSelectedItem(GestorCliente.getCLiente());
        cmbEmpleado.setSelectedItem(GestorEmpleado.getEmpleados());
        cmbServicio.setSelectedItem(GestorServicio.getServicios());
  
        this.menu = menu;
    }
    private void configurarTabla() {
        modelo = new DefaultTableModel();
        modelo.addColumn("ID Reserva");
        modelo.addColumn("Cliente");
        modelo.addColumn("Empleado");
        modelo.addColumn("Servicio");
        modelo.addColumn("Duracion");
        modelo.addColumn("Fecha/Hora entrada");
        modelo.addColumn("Fecha/Hora Salida");
        tblMostrarReservaciones.setModel(modelo);
    }
         private void refrescarTabla() {

    modeloTabla.setRowCount(0);
   
    for (Empleado empleado : listaEmpleado) {
        modeloTabla.addRow(new Object[]{
            empleado.getIdentificador(),
            empleado.getNombre(),
            empleado.getNumeroTelefono(),
            empleado.getEspecialidad()
        });}}
    
    private void cargarCombos() {
        // 1. Limpiar combos
        cmbCliente.removeAllItems();
        cmbEmpleado.removeAllItems();
        cmbServicio.removeAllItems();
        cmbEstado.removeAllItems();
        /*
        // 2. Llenar Clientes (Desde GestorDatos)
        ArrayList<Cliente> listaClientes = GestorDatos.getInstancia().clientes;
        for(Cliente cliente : listaClientes) {
            cmbCliente.addItem(cliente); // Agrega el OBJETO completo, no solo el nombre
        }
        
        // 3. Llenar Empleados
        ArrayList<Empleado> listaEmpleados = GestorDatos.getInstancia().empleados;
        for(Empleado e : listaEmpleados) {
            cmbEmpleado.addItem(e);
        }
        
        // 4. Llenar Servicios
        ArrayList<Servicio> listaServicios = GestorDatos.getInstancia().servicios;
        for(Servicio s : listaServicios) {
            cmbServicio.addItem(s);
        }
        
        // 5. Llenar Estados (Valores fijos)
        cmbEstado.addItem("Pendiente");
        cmbEstado.addItem("Confirmada");
        cmbEstado.addItem("Completada");
        cmbEstado.addItem("Cancelada"); */
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblGestiondeReservacion = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JPanel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblID = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblServicio = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        cmbServicio = new javax.swing.JComboBox<>();
        cmbEmpleado = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        cmbCliente = new javax.swing.JComboBox<>();
        spnFechaHora = new javax.swing.JSpinner();
        btnAgregar1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMostrarReservaciones = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGestiondeReservacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGestiondeReservacion.setForeground(new java.awt.Color(0, 153, 255));
        lblGestiondeReservacion.setText("Gestion de Reservacion");
        jPanel3.add(lblGestiondeReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 23, 206, -1));

        FondoBlanco.setBackground(new java.awt.Color(255, 255, 255));
        FondoBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        FondoBlanco.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("ID:");
        FondoBlanco.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 43, 50, -1));

        lblCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblCliente.setText("Cliente:");
        FondoBlanco.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 43, 60, -1));

        lblServicio.setForeground(new java.awt.Color(0, 0, 0));
        lblServicio.setText("Servicio");
        FondoBlanco.add(lblServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 95, 50, -1));

        lblEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpleado.setText("Empleado:");
        FondoBlanco.add(lblEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 70, -1));

        lblHora.setForeground(new java.awt.Color(0, 0, 0));
        lblHora.setText("Fecha y hora:");
        FondoBlanco.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, -1));

        estado.setForeground(new java.awt.Color(0, 0, 0));
        estado.setText("Estado:");
        FondoBlanco.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 76, -1));

        FondoBlanco.add(cmbServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 122, 90, 20));

        cmbEmpleado.setPreferredSize(new java.awt.Dimension(70, 20));
        FondoBlanco.add(cmbEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 110, -1));

        txtID.setColumns(5);
        FondoBlanco.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 63, 100, -1));

        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });
        FondoBlanco.add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 66, 110, 20));
        FondoBlanco.add(spnFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, -1));

        btnAgregar1.setText("Buscar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        FondoBlanco.add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 100, -1));
        FondoBlanco.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, -1));

        lblBuscar.setForeground(new java.awt.Color(0, 0, 0));
        lblBuscar.setText("Buscar:");
        FondoBlanco.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 80, -1));

        jPanel3.add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 66, 475, 310));

        tblMostrarReservaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Telefono", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMostrarReservaciones);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 570, 100));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 100, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 100, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 100, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed


    private void limpiarCampos() {
        txtID.setText("");
        txtBuscar.setText("");
        txtID.setEditable(true);
        if(cmbCliente.getItemCount() > 0) cmbCliente.setSelectedIndex(0);
        if(cmbEmpleado.getItemCount() > 0) cmbEmpleado.setSelectedIndex(0);
        if(cmbServicio.getItemCount() > 0) cmbServicio.setSelectedIndex(0);
        if(cmbEstado.getItemCount() > 0) cmbEstado.setSelectedIndex(0);
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int fila = tblMostrarReservaciones.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar este cliente?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                String id = txtID.getText();

                boolean ok = GestorCliente.eliminarCliente(id);

                if (ok) {
                    JOptionPane.showMessageDialog(this, "Servicio eliminado.");
                    refrescarTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar.");
                }

                limpiarCampos();
                refrescarTabla();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       new PanelMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoBlanco;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<Empleado> cmbEmpleado;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<Servicio> cmbServicio;
    private javax.swing.JLabel estado;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblGestiondeReservacion;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JSpinner spnFechaHora;
    private javax.swing.JTable tblMostrarReservaciones;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
