
package TP2_Grupo_AaronKevinRigoberto;

import javax.swing.JOptionPane;

/**
 *
 * @author kevin
 */
public class PanelMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PanelMenuPrincipal
     */
    public PanelMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblSistemaGestionDeReservas = new javax.swing.JLabel();
        btnGestionClientes = new javax.swing.JButton();
        btnGestionEmpleados = new javax.swing.JButton();
        btnGestionServicios = new javax.swing.JButton();
        btnGestionReservaciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblSistemaGestionDeReservas.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblSistemaGestionDeReservas.setForeground(new java.awt.Color(50, 150, 222));
        lblSistemaGestionDeReservas.setText("Sistema de Gestión de Reservaciones de Peluquería ");
        jPanel1.add(lblSistemaGestionDeReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnGestionClientes.setBackground(new java.awt.Color(102, 204, 255));
        btnGestionClientes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnGestionClientes.setForeground(java.awt.Color.white);
        btnGestionClientes.setText("Gestión De Clientes");
        btnGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 300, 100));

        btnGestionEmpleados.setBackground(new java.awt.Color(51, 153, 255));
        btnGestionEmpleados.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnGestionEmpleados.setForeground(java.awt.Color.white);
        btnGestionEmpleados.setText("Gestión De Empleados");
        btnGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 300, 100));

        btnGestionServicios.setBackground(new java.awt.Color(0, 153, 255));
        btnGestionServicios.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnGestionServicios.setForeground(java.awt.Color.white);
        btnGestionServicios.setText("Gestión De Servicios");
        btnGestionServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionServiciosActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 300, 100));

        btnGestionReservaciones.setBackground(new java.awt.Color(0, 102, 153));
        btnGestionReservaciones.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnGestionReservaciones.setForeground(java.awt.Color.white);
        btnGestionReservaciones.setText("Gestión De Reservaciones");
        btnGestionReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionReservacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestionReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 300, 100));

        btnSalir.setBackground(new java.awt.Color(0, 102, 102));
        btnSalir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSalir.setForeground(java.awt.Color.white);
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 300, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adobe Express - file (2).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionClientesActionPerformed
     GestionDeClientes gestionCliente = new GestionDeClientes(this);
     gestionCliente.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_btnGestionClientesActionPerformed

    private void btnGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionEmpleadosActionPerformed
     GestionDeEmpleados gestionEmpleado = new GestionDeEmpleados(this);
     gestionEmpleado.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_btnGestionEmpleadosActionPerformed

    private void btnGestionReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionReservacionesActionPerformed
     GestionDeReservaciones gestionReservaciones = new GestionDeReservaciones(this);
     gestionReservaciones .setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_btnGestionReservacionesActionPerformed

    private void btnGestionServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionServiciosActionPerformed
     GestionDeServicios gestionServicios = new GestionDeServicios(this);
     gestionServicios.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_btnGestionServiciosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
     JOptionPane.showMessageDialog(this, "Muchas gracias por usar nuestro sistema de peluqueria "
             +"\n" + " Vuelva pronto ");
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionClientes;
    private javax.swing.JButton btnGestionEmpleados;
    private javax.swing.JButton btnGestionReservaciones;
    private javax.swing.JButton btnGestionServicios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSistemaGestionDeReservas;
    // End of variables declaration//GEN-END:variables
}
